service: notes-manager
plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dynamodb-local

functions:
  app:
    handler: dist/main.handler
    events:
      - http:
          method: any
          path: /{any+}

provider:
  name: aws
  runtime: nodejs16.x
  apiGateway:
    shouldStartNameWithService: true

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:DescribeTable'
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'

          Resource: arn:aws:dynamodb:us-west-2:*:table/BlogsTable

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: [aws-sdk]
    target: node16
    define: 'require.resolve: undefined'
    platform: node
    concurrency: 10

  dynamodb:
    start:
      port: 5000
      inMemory: true
      migrate: true

    stages: dev
